title: AI and Sociology
author: Alba Roza
theme: minima
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Some thoughts on how Artificial Intelligence impacts in Society, wether those cases are good or not. 

# social links
twitter_username: Alba_Roza
github_username:  AlbaRoza
show_excerpts: true # set to false to remove excerpts on the homepage
